/*KARGO*/
SELECT COM,PLANT,TIPE_TRUK,TGL_SPJ,DATE_CVY,TGL_ANTRI
from ZREPORT_RPT_REAL
where (SELECT TO_CHAR (SYSDATE-1, 'DD-MM-YYYY') "NOW" FROM DUAL) = TO_CHAR(TGL_SPJ, 'DD-MM-YYYY')
and STATUS<=40 and STATUS>=10;

SELECT COUNT(NO_TRANSAKSI),TIPE_TRUK FROM ZREPORT_RPT_REAL_NON70
WHERE (SELECT TO_CHAR (SYSDATE, 'DD-MM-YYYY') "NOW" FROM DUAL) = TO_CHAR(TGL_SPJ, 'DD-MM-YYYY')
and STATUS<=40 and STATUS>=10
GROUP BY TIPE_TRUK;